// get semua users
GET http://localhost:5000/users


// get single users
###
GET http://localhost:5000/users/895d8352-6dfb-4c2a-adf4-b5992ecb5f69


//Buat User Role Admin
//Ketika pertama kali menjalankan aplikasi, hapus middleware di UserRoute.
### 
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Helmi", 
    "email": "helmibe48@gmail.com",
    "password": "123456",
    "confPassword": "123456",
    "role": "admin"
}

//Buat User Role User
### 
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Qtasnim", 
    "email": "qtasnim@gmail.com",
    "password": "123456",
    "confPassword": "123456",
    "role": "user"
}

//update user
### 
PATCH http://localhost:5000/users/895d8352-6dfb-4c2a-adf4-b5992ecb5f69
Content-Type: application/json

{
    "name": "PTBA", 
    "email": "ptba@gmail.com",
    "password": "",
    "confPassword": "",
    "role": "user"
}

//delete user
### 
DELETE http://localhost:5000/users/895d8352-6dfb-4c2a-adf4-b5992ecb5f69

###
//login user
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "helmibe48@gmail.com",
    "password": "123456"
}

###
//Lihat siapa yang login
GET http://localhost:5000/me

###
//Logout Akun
DELETE http://localhost:5000/logout


###
// Get Semua Produlk
GET http://localhost:5000/products

###
// Get Satu Produk
GET http://localhost:5000/products/62345c35-e3f0-4978-81f3-6c22fcf1574a

###
// Tambah Data Produk
POST http://localhost:5000/products
Content-Type: application/json

{
    "name": "Minyak",
    "price": "150000"
}

###
// Update Data Produk
PATCH http://localhost:5000/products/62345c35-e3f0-4978-81f3-6c22fcf1574a
Content-Type: application/json

{
    "name": "Minyak diupdate",
    "price": "150000"
}

###
// Hapus Data Produk
DELETE http://localhost:5000/products/62345c35-e3f0-4978-81f3-6c22fcf1574a